### ISSUE TITLE
Website not rendering

### ISSUE THREAD

**Issue by Visible-Break** [firebase/emulators-codelab#12] opened 2021-01-18 18:43 UTC
Following along with both the text & video tutorials, when trying to view the webpage using the emulator the page throws a bunch of errors and does not render. 

I encounter the same issue when running emulators:start on both the /codelab-initial-state/ and /codelab-final-state/ folders. 

![Capture](https://user-images.githubusercontent.com/77638309/104952747-17d79100-5993-11eb-8464-a9df7331b0ee.JPG)

**Comment by samtstern** [comment] 2021-01-19 15:01
@Visible-Break I'm not able to reproduce this.  Here's what I did:

1. Clone this repo
2. `cd codelab-final-state`
3. `cd functions && npm install && cd ../`
4. `firebase emulators:start`
5. Navigate to `localhost:5000`

And here's what I see:
<img width="721" alt="Screen Shot 2021-01-19 at 3 00 51 PM" src="https://user-images.githubusercontent.com/8466666/105051987-575ab780-5a3d-11eb-9b38-a5ec5fa2bd07.png">

**Comment by Visible-Break** [comment] 2021-01-20 17:10
Hi samtstern, thanks for the reply & trying to work with me on this.

So I started over again - started by navigating to the folder where I've been keeping my local version of the repo and deleting all files, as well as deleting my firebase project previously setup for this tutorial. 

Then following along with the tutorial, 
1. checked the version of java on my machine - version 15.0.1
2. checked the version of node on my machine - version 12.18.4
3. created a new Firebase project (with Google Analytics disabled)
4. enabled anonymous authentication 
5. `git clone https://github.com/firebase/emulators-codelab.git`
6. `cd emulators-codelab\codelab-final-state`
7. For some reason the && operation doesn't work for me in VSCode terminal, so I executed the package install as 3 steps: `cd functions` -> `npm install` -> `cd ..` [note that "requested 'node' version '10' doesn't match your global version '12' "]
8. `firebase emulators:start`
9. Java.exe window opens, navigating to localhost:5000 - website looks functional as you see as well. 
8. Returning to the tutorial instructions, closed emulators from terminal (ctrl+c) and closed Java.exe window.
9. `npm install firebase-tools`
9. checked the version of firebase available - version 9.2.1
10. `firebase login`
11. `firebase use --add` -> select dedicated Firebase project created earlier, entered "default" for alias to be used.
12. `firebase emulators:start --import=./seed`
13. Java.exe window opens, navigating to localhost:5000 - website still looks functional, now with seed data being accessed.
14. close emulators from terminal (ctrl+c) and closed Java.exe window.
15. cd into codelab-initial-state\functions
16. `npm install` -> `cd ..`
17. `npm install firebase-tools` -> firebase version 9.2.1 verified
18. `firebase login`
11. `firebase use --add` -> select dedicated Firebase project created earlier, entered "default" for alias to be used.
12. `firebase emulators:start --import=./seed`
13. Java.exe window opens, navigating to localhost:5000 - website still looks functional, however seed data is not available (because I didn't do the frontend-emulator connection step)

Well, I hate to admit it, but I can't recreate the issue I was having either, though I don't notice anything different that I'm doing today that I didn't do the first or second time before opening this issue.

Only thing I can think of is that I had just installed Java for the first time that day, so maybe there were some setup operations completed over the course of a few shut down / turn on cycles since then (?)

**Comment by samtstern** [comment] 2021-01-20 17:22
@Visible-Break thank you for such a detailed follow up!  I am glad it's working now.

**Comment by Visible-Break** [comment] 2021-01-21 15:53
Is the firebase emulator meant to work in an incognito window?

Was hitting some cache annoyances (launching from initial-state folder was continuing to bring in some of the code from final-state), so I wanted to move to incognito mode but neither final-state nor initial-state will launch properly. 

Funny enough, these errors look the same as what I was encountering when I first opened this issue, although that was in a standard Chrome tab.

![Capture](https://user-images.githubusercontent.com/77638309/105375348-a556f300-5bd6-11eb-93dc-618c2761edce.JPG)

**Comment by samtstern** [comment] 2021-01-21 16:10
@Visible-Break I think we have an issue in recent versions of `firebase-tools` that is causing this, see:
https://github.com/firebase/firebase-tools/pull/3065

For now I'd say you should downgrade to `firebase-tools` `9.1.0` or so until we get the bug fix out.  Closing this issue here as I think we're tracking it over there.

**Closed by samtstern** 2021-01-21 16:10 UTC
Labels: needs-info

**Comment by samtstern** [comment] 2021-01-22 10:45
@Visible-Break we released a new version of `firebase-tools` last night with a fix for this bug, so if you upgrade to the latest everything should work!
